name = "traducteur-bot-rs"
main = "build/index.js"
compatibility_date = "2026-07-06"
route = { pattern = "traducteur.hash.moe", custom_domain = true }
workers_dev = false

[build]
command = "worker-build --release --panic-unwind"

[observability.logs]
enabled = true
